name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for Lint
        uses: chartboost/ruff-action@v1

      - name: Check Formatting
        uses: chartboost/ruff-action@v1
        with:
          args: format --check

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install DynamoDB
        id: install-dynamodb
        uses: ./.github/actions/install-dynamodb

      - name: Install Package
        run: pip install pytest-cov -e .[test]

      - name: Run Tests
        run: pytest --dynamodb-dir=${{ steps.install-dynamodb.outputs.dynamodb-dir }} --cov --cov-report=xml

      - name: Upload to Codecov.io
        uses: codecov/codecov-action@v3

      - name: Check Types
        run: pip install mypy && mypy .
